export const storeConfig = {
  name: "Chapati and Melfouf",
  tagline: "???? ??????? ???????? ?? ?????? - ???? ????!",
  whatsappNumber: "213558447723",
  address: "??????? ????? ???????",
  hours: "?? ??? ?? 11:00 ??? 23:00",
  deliveryFee: 150,
};

export const heroImage =
  "https://images.unsplash.com/photo-1763951719324-d1ff7eff0f7b?auto=format&fit=crop&w=1600&q=70";

export const themes = {
  violet: { from: "#2c1a5c", to: "#5b2a86" },
  ember: { from: "#7a1220", to: "#e8622c" },
  charcoal: { from: "#1c1712", to: "#3a2c22" },
  olive: { from: "#22280f", to: "#93a33a" },
  crimson: { from: "#5c0f18", to: "#b8202c" },
};

const specialOptions = [
  { id: "cheese", name: "????", price: 50 },
  { id: "comopair", name: "???????", price: 100 },
  { id: "extra-scalope", name: "????? ??????", price: 50 },
  { id: "extra-kebda", name: "????? ????", price: 50 },
];

export const menuGroups = [
  {
    id: "chapati-normal",
    title: "??????? ??????",
    items: [
      {
        id: "chapati-scalope",
        name: "????? ??????",
        desc: "????? ?????? ?? ?????? ?????",
        price: 200,
        theme: "violet",
        image: "/chapati-/images/01-chapati-scalope.webp",
      },
      {
        id: "chapati-kebda",
        name: "????? ????",
        desc: "????? ???? ?? ?????? ?????",
        price: 200,
        theme: "ember",
        image: "/chapati-/images/02-chapati-kebda.webp",
      },
      {
        id: "chapati-mix",
        name: "????? ????",
        desc: "????? ???? ?? ?????? ?????",
        price: 200,
        theme: "charcoal",
        image: "/chapati-/images/03-chapati-mix.webp",
      },
      {
        id: "chapati-simple-scalope",
        name: "????? ????? ??????",
        desc: "????? ????? ??????",
        price: 150,
        theme: "olive",
        image: "/chapati-/images/04-chapati-simple-scalope.webp",
      },
    ],
  },

  {
    id: "chapati-special",
    title: "??????? ?????????",
    items: [
      {
        id: "special-scalope",
        name: "????? ??????? ??????",
        desc: "????? ??????? ?? ?????? ????????",
        price: 200,
        theme: "violet",
        image: "/chapati-/images/05-chapati-special-scalope.webp",
        options: specialOptions,
      },
      {
        id: "special-kebda",
        name: "????? ??????? ????",
        desc: "????? ??????? ?? ?????? ????????",
        price: 200,
        theme: "ember",
        image: "/chapati-/images/06-chapati-special-kebda.webp",
        options: specialOptions,
      },
      {
        id: "special-mix",
        name: "????? ??????? ????",
        desc: "????? ??????? ?? ?????? ????????",
        price: 200,
        theme: "crimson",
        image: "/chapati-/images/07-chapati-special-mix.webp",
        options: specialOptions,
      },
    ],
  },

  {
    id: "malfouf",
    title: "???????",
    items: [
      {
        id: "malfouf-scalope",
        name: "????? ??????",
        desc: "????? ?? ?????? ??????? ????????",
        price: 200,
        theme: "olive",
        image: "/chapati-/images/08-malfouf-scalope.webp",
        options: specialOptions,
      },
      {
        id: "malfouf-kebda",
        name: "????? ????",
        desc: "????? ?? ???? ??????? ????????",
        price: 200,
        theme: "ember",
        image: "/chapati-/images/09-malfouf-kebda.webp",
        options: specialOptions,
      },
      {
        id: "malfouf-mix",
        name: "????? ????",
        desc: "????? ???? ??????? ????????",
        price: 200,
        theme: "crimson",
        image: "/chapati-/images/10-malfouf-mix.webp",
        options: specialOptions,
      },
      {
        id: "malfouf-special-scalope",
        name: "????? ??????? ??????",
        desc: "????? ??????? ?? ?????? ????????",
        price: 200,
        theme: "violet",
        image: "/chapati-/images/11-malfouf-special-scalope.webp",
        options: specialOptions,
      },
      {
        id: "malfouf-special-kebda",
        name: "????? ??????? ????",
        desc: "????? ??????? ?? ?????? ????????",
        price: 200,
        theme: "ember",
        image: "/chapati-/images/12-malfouf-special-kebda.webp",
        options: specialOptions,
      },
      {
        id: "malfouf-special-mix",
        name: "????? ??????? ????",
        desc: "????? ??????? ???? ?? ?????? ????????",
        price: 200,
        theme: "crimson",
        image: "/chapati-/images/13-malfouf-special-mix.webp",
        options: specialOptions,
      },
    ],
  },

  {
    id: "drinks",
    title: "?????????",
    items: [
      {
        id: "coca-cola-large",
        name: "Coca-Cola",
        desc: "????",
        price: 130,
        theme: "crimson",
        image: "/chapati-/images/14-coca-cola.webp",
      },
      {
        id: "pepsi-large",
        name: "Pepsi",
        desc: "????",
        price: 100,
        theme: "violet",
        image: "/chapati-/images/15-pepsi.jpg",
      },
      {
        id: "mirinda-large",
        name: "Mirinda",
        desc: "????",
        price: 100,
        theme: "ember",
        image: "/chapati-/images/16-mirinda.webp",
      },
      {
        id: "hamoud-large",
        name: "Hamoud",
        desc: "????",
        price: 100,
        theme: "olive",
        image: "/chapati-/images/17-hamoud.webp",
      },
      {
        id: "schweppes-large",
        name: "Schweppes",
        desc: "????",
        price: 1500,
        theme: "charcoal",
        image: "/chapati-/images/18-schweppes.webp",
      },
      {
        id: "ifri-large",
        name: "Ifri Juice",
        desc: "????",
        price: 150,
        theme: "olive",
        image: "/chapati-/images/19-ifri.webp",
      },
      {
        id: "bona-large",
        name: "Bona",
        desc: "????",
        price: 100,
        theme: "ember",
        image: "/chapati-/images/20-bona.webp",
      },
      {
        id: "water-large",
        name: "???",
        desc: "????",
        price: 400,
        theme: "violet",
        image: "/chapati-/images/21-water.webp",
      },

      {
        id: "coca-cola-mini",
        name: "Coca-Cola",
        desc: "Mini",
        price: 60,
        theme: "crimson",
        image: "/chapati-/images/14-coca-cola.webp",
      },
      {
        id: "pepsi-mini",
        name: "Pepsi",
        desc: "Mini",
        price: 60,
        theme: "violet",
        image: "/chapati-/images/15-pepsi.jpg",
      },
      {
        id: "mirinda-mini",
        name: "Mirinda",
        desc: "Mini",
        price: 60,
        theme: "ember",
        image: "/chapati-/images/16-mirinda.webp",
      },
      {
        id: "hamoud-mini",
        name: "Hamoud",
        desc: "Mini",
        price: 60,
        theme: "olive",
        image: "/chapati-/images/17-hamoud.webp",
      },
      {
        id: "schweppes-mini",
        name: "Schweppes",
        desc: "Mini",
        price: 70,
        theme: "charcoal",
        image: "/chapati-/images/18-schweppes.webp",
      },
      {
        id: "ifri-mini",
        name: "Ifri Juice",
        desc: "Mini",
        price: 60,
        theme: "olive",
        image: "/chapati-/images/19-ifri.webp",
      },
      {
        id: "bona-mini",
        name: "Bona",
        desc: "Mini",
        price: 50,
        theme: "ember",
        image: "/chapati-/images/20-bona.webp",
      },
      {
        id: "water-mini",
        name: "???",
        desc: "Mini",
        price: 25,
        theme: "violet",
        image: "/chapati-/images/21-water.webp",
      },
    ],
  },
];

export const sauces = [
  { id: "spicy", name: "???? ????", price: 0 },
  { id: "mayonnaise", name: "???????", price: 0 },
];

export const deliveryZones = [
  "??????",
  "????",
  "???? ????",
  "??? ?????",
  "??????",
];
