export const storeConfig = {
  name: "Chapati and Melfouf",
  tagline: "أطيب الشباتي والملفوف في العلمة - اطلب الآن!",
  whatsappNumber: "213558447723",
  address: "العلمة، سطيف، الجزائر",
  hours: "كل يوم من 11:00 إلى 23:00",
  deliveryFee: 150,
  ownerPassword: "ahlachapati1",
};

export const heroImage =
  "https://images.unsplash.com/photo-1763951719324-d1ff7eff0f7b?auto=format&fit=crop&w=1600&q=70";

export const themes = {
  violet: { from: "#2c1a5c", to: "#5b2a86" },
  ember: { from: "#7a1220", to: "#e8622c" },
  charcoal: { from: "#1c1712", to: "#3a2c22" },
  olive: { from: "#22280f", to: "#93a33a" },
  crimson: { from: "#5c0f18", to: "#b8202c" },
};

export const menuGroups = [
  {
    id: "chapati-normal",
    title: "شبتي",
    items: [
      {
        id: "chapati-scalope",
        name: "شباتي سكالوب",
        desc: "شباتي سكالوب مع اختيار الصوص",
        price: 200,
        theme: "violet",
        image: "/chapati-/images/01-chapati-scalope.webp",
        customization: "normal",
      },
      {
        id: "chapati-kebda",
        name: "شباتي كبدة",
        desc: "شباتي كبدة مع اختيار الصوص",
        price: 200,
        theme: "ember",
        image: "/chapati-/images/02-chapati-kebda.webp",
        customization: "normal",
      },
      {
        id: "chapati-mix",
        name: "شباتي ميكس",
        desc: "شباتي ميكس مع اختيار الصوص",
        price: 200,
        theme: "charcoal",
        image: "/chapati-/images/03-chapati-mix.webp",
        customization: "normal",
      },
      {
        id: "chapati-simple-scalope",
        name: "شباتي سامبل سكالوب",
        desc: "شباتي سامبل سكالوب",
        price: 150,
        theme: "olive",
        image: "/chapati-/images/04-chapati-simple-scalope.webp",
        customization: "normal",
      },
      {
        id: "special-scalope",
        name: "شباتي سبيسيال سكالوب",
        desc: "شيزي 250 دج أو كوموبير 300 دج",
        price: 250,
        theme: "violet",
        image: "/chapati-/images/05-chapati-special-scalope.webp",
        customization: "chapati-special",
        type: "سكالوب",
      },
      {
        id: "special-kebda",
        name: "شباتي سبيسيال كبدة",
        desc: "شيزي 250 دج أو كوموبير 300 دج",
        price: 250,
        theme: "ember",
        image: "/chapati-/images/06-chapati-special-kebda.webp",
        customization: "chapati-special",
        type: "كبدة",
      },
      {
        id: "special-mix",
        name: "شباتي سبيسيال ميكس",
        desc: "شيزي 250 دج أو كوموبير 300 دج",
        price: 250,
        theme: "crimson",
        image: "/chapati-/images/07-chapati-special-mix.webp",
        customization: "chapati-special",
        type: "ميكس",
      },
    ],
  },

  {
    id: "malfouf",
    title: "الملفوف",
    items: [
      {
        id: "malfouf-scalope",
        name: "ملفوف سكالوب",
        desc: "ملفوف سكالوب مع اختيار الصوص",
        price: 250,
        theme: "olive",
        image: "/chapati-/images/08-malfouf-scalope.webp",
        customization: "normal",
      },
      {
        id: "malfouf-kebda",
        name: "ملفوف كبدة",
        desc: "ملفوف كبدة مع اختيار الصوص",
        price: 250,
        theme: "ember",
        image: "/chapati-/images/09-malfouf-kebda.webp",
        customization: "normal",
      },
      {
        id: "malfouf-mix",
        name: "ملفوف ميكس",
        desc: "ملفوف ميكس مع اختيار الصوص",
        price: 250,
        theme: "crimson",
        image: "/chapati-/images/10-malfouf-mix.webp",
        customization: "normal",
      },
      {
        id: "malfouf-special-scalope",
        name: "ملفوف سبيسيال سكالوب",
        desc: "شيزي 300 دج أو كوموبير 350 دج",
        price: 300,
        theme: "violet",
        image: "/chapati-/images/11-malfouf-special-scalope.webp",
        customization: "malfouf-special",
        type: "سكالوب",
      },
      {
        id: "malfouf-special-kebda",
        name: "ملفوف سبيسيال كبدة",
        desc: "شيزي 300 دج أو كوموبير 350 دج",
        price: 300,
        theme: "ember",
        image: "/chapati-/images/12-malfouf-special-kebda.webp",
        customization: "malfouf-special",
        type: "كبدة",
      },
      {
        id: "malfouf-special-mix",
        name: "ملفوف سبيسيال ميكس",
        desc: "شيزي 300 دج أو كوموبير 350 دج",
        price: 300,
        theme: "crimson",
        image: "/chapati-/images/13-malfouf-special-mix.webp",
        customization: "malfouf-special",
        type: "ميكس",
      },
    ],
  },

  {
    id: "drinks",
    title: "المشروبات",
    items: [
      {
        id: "coca-cola-large",
        name: "Coca-Cola",
        desc: "اختر الحجم",
        price: 130,
        theme: "crimson",
        image: "/chapati-/images/14-coca-cola.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 130 },
          { id: "mini", name: "Mini", price: 60 },
        ],
      },
      {
        id: "pepsi-large",
        name: "Pepsi",
        desc: "اختر الحجم",
        price: 100,
        theme: "violet",
        image: "/chapati-/images/15-pepsi.jpg",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 100 },
          { id: "mini", name: "Mini", price: 60 },
        ],
      },
      {
        id: "mirinda-large",
        name: "Mirinda",
        desc: "اختر الحجم",
        price: 100,
        theme: "ember",
        image: "/chapati-/images/16-mirinda.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 100 },
          { id: "mini", name: "Mini", price: 60 },
        ],
      },
      {
        id: "hamoud-large",
        name: "Hamoud",
        desc: "اختر الحجم",
        price: 100,
        theme: "olive",
        image: "/chapati-/images/17-hamoud.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 100 },
          { id: "mini", name: "Mini", price: 60 },
        ],
      },
      {
        id: "schweppes-large",
        name: "Schweppes",
        desc: "اختر الحجم",
        price: 150,
        theme: "charcoal",
        image: "/chapati-/images/18-schweppes.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 150 },
          { id: "mini", name: "Mini", price: 70 },
        ],
      },
      {
        id: "ifri-large",
        name: "Ifri Juice",
        desc: "اختر الحجم",
        price: 150,
        theme: "olive",
        image: "/chapati-/images/19-ifri.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 150 },
          { id: "mini", name: "Mini", price: 60 },
        ],
      },
      {
        id: "bona-large",
        name: "Bona",
        desc: "اختر الحجم",
        price: 100,
        theme: "ember",
        image: "/chapati-/images/20-bona.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 100 },
          { id: "mini", name: "Mini", price: 50 },
        ],
      },
      {
        id: "water-large",
        name: "ماء",
        desc: "اختر الحجم",
        price: 50,
        theme: "violet",
        image: "/chapati-/images/21-water.webp",
        customization: "drink",
        drinkSizes: [
          { id: "large", name: "كبير", price: 50 },
          { id: "mini", name: "Mini", price: 30 },
        ],
      },
    ],
  },
];

export const sauces = [
  { id: "mayonnaise", name: "\u0645\u0627\u064a\u0648\u0646\u064a\u0632", price: 0 },
  { id: "harissa", name: "\u0647\u0631\u064a\u0633\u0629", price: 0 },
];

export const deliveryZones = [
  "العلمة",
  "قجال",
  "بازر سكرة",
  "بئر العرش",
  "الزرقة",
];


